# Assignment 1
The objective of this assignment is to enhance your proficiency with the NumPy library by engaging in a series of tasks encompassing diverse operations, statistical analyses, and indexing/slicing procedures. Through the completion of these tasks, you are expected to reinforce your understanding of NumPy functionalities and sharpen your skills in leveraging the library for effective data manipulation.

**Instructions:**
  - Do not remove comments such as # Task 1.1,# Task 1.2 etc. Provide your answers bellow these comments.
  - Use the provided variable names for your answers.
  - If the question is related to numpy operations, you are not allowed to use for loops.


**Task 1: Basic NumPy Operations (10 points)**
1. Create a NumPy array with the values `[1, 2, 3, 4, 5]`. Name this array `arr1`. (1pt)
2. Create another NumPy array with the values `[6, 7, 8, 9, 10]`. Name this array `arr2`. (1pt)
3. Perform element-wise addition, subtraction, multiplication, and division on `arr1` and `arr2`. Store the results in new arrays. (8pts)

In [5]:
import numpy as np

# Task 1.1
arr1 = np.array([1,2,3,4,5])

# Task 1.2
arr2 = np.array([6,7,8,9,10])

# Task 1.3
addition_result = arr1 + arr2
subtraction_result = arr1 - arr2
multiplication_result = arr1 * arr2
division_result = arr1 / arr2

print (addition_result)
print (subtraction_result)
print (multiplication_result)
print (division_result)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


**Task 2: Statistical Analysis (20 points)**
1. Create a random NumPy array with 100 elements sampled from a normal distribution with mean 50 and standard deviation 10. Name this array `data`. (5pts)
2. Calculate and print the mean, median, and standard deviation of the `data` array. (5pts)
3. Reshape the `data` array into a 10x10 matrix. (5pts)
4. Find the minimum and maximum values in each row and each column of the reshaped matrix. (5pts)

In [7]:
# Task 2.1
data = np.random.normal(50,10,100)

# Task 2.2
mean_value = np.mean(data)
median_value = np.median(data)
std_deviation = np.std(data)

# Task 2.3
reshaped_data = data.reshape(10,10)

# Task 2.4
min_values_by_row =  np.min(reshaped_data, axis=1)
max_values_by_row =  np.max(reshaped_data, axis=1)
min_values_by_col =  np.min(reshaped_data, axis=0)
max_values_by_col = np.max(reshaped_data, axis=0)

print(mean_value)
print(median_value)
print(std_deviation)
print(reshaped_data)
print(min_values_by_row)
print(max_values_by_row)
print(min_values_by_col)
print(max_values_by_col)


50.83555326484913
50.22127344731204
10.063624311284189
[[56.88467143 61.67791778 45.69839301 44.55252298 53.80015773 60.32918311
  46.7108695  47.06254451 61.02486737 54.28958981]
 [40.46689824 55.26087176 49.408358   52.26872553 64.10831193 43.48788781
  64.88379481 40.3543742  48.11639389 48.00685661]
 [47.55790729 52.50533443 51.44749287 48.07243091 57.76006192 42.36322463
  46.35580225 53.49110292 68.3519912  54.52489745]
 [54.13414988 44.5877294  53.72910671 62.53461095 50.28538851 29.39346551
  53.75507277 24.10686562 57.95311711 57.50712164]
 [64.86409005 43.02978526 47.71548848 38.34381436 46.58543381 28.31098578
  67.27469261 37.95931795 38.22685747 53.66871762]
 [54.16926282 23.33274669 59.96099541 44.88541122 47.04924916 52.13372726
  50.15715839 46.33465262 42.63648575 68.07725131]
 [54.24235024 58.33302485 54.09502405 49.75636304 64.94485086 48.3804737
  70.40503011 45.34750579 56.66273818 64.07310465]
 [43.53337743 36.94044235 46.96507092 43.64066638 61.68063384 41.591776

**Task 3: NumPy Indexing and Slicing (35 points)**
1. Create a NumPy array with values `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]`. Name this array `arr3`. (1pt)
2. Print the even elements of `arr3`. (10pts)
3. Print the elements greater than 5 in `arr3`. (10pts)
4. Reshape `arr3` into a 2x5 matrix. (4pts)
5. Extract the second column of the reshaped matrix. (10pts)

In [9]:
# Task 3.1
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_elems = arr3[arr3 % 2 == 0]

# Task 3.2
elements_greater_than_5 = arr3[arr3 > 5]

# Task 3.3
reshaped_arr3 = arr3.reshape(2, 5)

# Task 3.4
second_column = reshaped_arr3[:, 1]

print(even_elems)
print(elements_greater_than_5)
print(reshaped_arr3)
print(second_column)

[ 2  4  6  8 10]
[ 6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[2 7]


 **Task 4: Axis Operations: (35pts)**
    
1. Create a 2D NumPy array with shape (4, 5) containing random integers. (5pts)
2. Calculate the sum of each column and find the column index with the maximum sum. (10pts)
3. Calculate the mean of each row and find the row index with the minimum mean. (10pts)
4. Normalize the values of each column by subtracting the mean and dividing by the standard deviation of the column. (10pts)

In [10]:
# Task 4.1
array_2d = np.random.randint(1, 100, (4, 5))


# Task 4.2
column_sums = np.sum(array_2d, axis=0)
max_sum_column_index = np.argmax(column_sums)


# Task 4.3
row_means = np.mean(array_2d, axis=1)
min_mean_row_index = np.argmin(row_means)

# Task 4.4
column_means = np.mean(array_2d, axis=0)
column_std_devs = np.std(array_2d, axis=0)
normalized_array = (array_2d - column_means) / column_std_devs

print("2D Array:\n", array_2d)
print("Column sums:", column_sums)
print("Index of the column with the maximum sum:", max_sum_column_index)
print("Row means:", row_means)
print("Index of the row with the minimum mean:", min_mean_row_index)
print("Normalized array:\n", normalized_array)

2D Array:
 [[68 92 21 85 72]
 [11 55 88 71  5]
 [37 61 57 49 60]
 [78 43 99 81 34]]
Column sums: [194 251 265 286 171]
Index of the column with the maximum sum: 3
Row means: [67.6 46.  52.8 67. ]
Index of the row with the minimum mean: 1
Normalized array:
 [[ 0.73848274  1.61706515 -1.49210176  0.96737539  1.13538735]
 [-1.42015912 -0.42845316  0.71719808 -0.03582872 -1.46532897]
 [-0.43551546 -0.09674749 -0.30501528 -1.61229232  0.66958741]
 [ 1.11719184 -1.09186451  1.07991895  0.68074565 -0.33964579]]
